version: '3'

services:
  postgres:
    image: 'postgres:14-alpine'
    container_name: 'postgres_db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0542'
      - 'POSTGRES_DB=shop'
    networks:
      - 'shop-network'

  app:
    build: ./
    container_name: 'spring_main'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    networks:
      - 'shop-network'

networks:
  shop-network:
    driver: 'bridge'